In [1]:
#분류가 목적
#베이즈 정리를 적용한 확률적 분류 기법

#사전확률을 통해 사후확률을 예측.

In [2]:
import numpy as np
X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
y = np.array([1,1,1,2,2,2,])

In [22]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

clf = GaussianNB()
clf.fit(X, y)

clf2 = BernoulliNB()
clf2.fit(X, y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [6]:
print(clf.predict([[-0.8, -1]]))
print(clf2.predict([[-0.8, -1]]))

[1]
[1]


In [18]:
clf_pf = GaussianNB()
clf_pf.partial_fit(X,y, np.unique(y))

GaussianNB(priors=None)

In [31]:
X = np.random.randint(2, size =[6,100])
y = np.array([1,2,3,4,4,5])
X

array([[0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
        0, 1, 0, 0, 0,

In [20]:
clf = BernoulliNB()
clf.fit(X,y)

print(clf.predict(X[2:3]))

[3]


In [24]:
X = np.random.randint(3, size =(6, 100))
y = np.array([1,2,3,4,4,5])


clf = MultinomialNB()
clf.fit(X,y)

print(clf.predict(X[2:3]))

[3]


In [33]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

import pandas as pd
import numpy as np

In [36]:
tennis_data = pd.read_csv("../9 - Data/playTennis.csv")
tennis_data

outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [38]:
tennis_data.columns = ['Outlook', "Temperature", "Humidity", "Wind", "PlayTennis"]

In [39]:
tennis_data.Outlook = tennis_data.Outlook.replace("Sunny", 0)
tennis_data.Outlook = tennis_data.Outlook.replace("Overcast", 1)
tennis_data.Outlook = tennis_data.Outlook.replace("Rain", 2)

tennis_data.Temperature = tennis_data.Outlook.replace("Hot", 3)
tennis_data.Temperature = tennis_data.Outlook.replace("Mild", 4)
tennis_data.Temperature = tennis_data.Outlook.replace("Cool", 5)

tennis_data.Humidity = tennis_data.Humidity.replace("High", 6)
tennis_data.Humidity = tennis_data.Humidity.replace("Normal", 7)

tennis_data.Wind = tennis_data.Wind.replace("Weak", 8)
tennis_data.Wind = tennis_data.Wind.replace("Strong", 9)

tennis_data.PlayTennis = tennis_data.PlayTennis.replace("No", 10)
tennis_data.PlayTennis = tennis_data.PlayTennis.replace("Yes", 11)

tennis_data

Outlook  Temperature  Humidity  Wind  PlayTennis
0         0            0         6     8          10
1         0            0         6     9          10
2         1            1         6     8          11
3         2            2         6     8          11
4         2            2         7     8          11
5         2            2         7     9          10
6         1            1         7     9          11
7         0            0         6     8          10
8         0            0         7     8          11
9         2            2         7     8          11
10        0            0         7     9          11
11        1            1         6     9          11
12        1            1         7     8          11
13        2            2         6     9          10

In [46]:
X= np.array(pd.DataFrame(tennis_data, columns=["Outlook", "Temperature", "Humidity", "Wind"]))
y= np.array(pd.DataFrame(tennis_data, columns=["PlayTennis"]))

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X,y)
X_train, X_test, y_train, y_test

(array([[2, 2, 7, 8],
        [2, 2, 7, 8],
        [1, 1, 6, 9],
        [0, 0, 6, 8],
        [2, 2, 6, 8],
        [0, 0, 7, 9],
        [0, 0, 6, 9],
        [1, 1, 7, 8],
        [2, 2, 6, 9],
        [1, 1, 7, 9]], dtype=int64), array([[0, 0, 6, 8],
        [0, 0, 7, 8],
        [2, 2, 7, 9],
        [1, 1, 6, 8]], dtype=int64), array([[11],
        [11],
        [11],
        [10],
        [11],
        [11],
        [10],
        [11],
        [10],
        [11]], dtype=int64), array([[10],
        [11],
        [10],
        [11]], dtype=int64))

In [48]:
gnb_clf = GaussianNB()
gnb_clf = gnb_clf.fit(X_train, y_train)

C:\Users\hyunseok\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [49]:
gnb_prediction = gnb_clf.predict(X_test)

In [56]:
print(gnb_prediction)
print(y_test)

[10 11 11 10]
[[10]
 [11]
 [10]
 [11]]


In [55]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

print('Confusion Matrix')
print(confusion_matrix(y_test, gnb_prediction))

print("\n\nClassification Report")
print(classification_report(y_test, gnb_prediction))

fmeaure = round(f1_score(y_test, gnb_prediction, average = 'weighted'), 2)
accuracy = round(accuracy_score(y_test, gnb_prediction, normalize= True), 2)

df_nbclf = pd.DataFrame(columns=['Classifier', 'F-measure', 'Accuracy'])
df_nbclf.loc[len(df_nbclf)] = ["Naive Bayes", fmeaure, accuracy]
df_nbclf

Confusion Matrix
[[1 1]
 [1 1]]


Classification Report
             precision    recall  f1-score   support

         10       0.50      0.50      0.50         2
         11       0.50      0.50      0.50         2

avg / total       0.50      0.50      0.50         4



Classifier  F-measure  Accuracy
0  Naive Bayes        0.5       0.5