In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm, datasets
%matplotlib inline

In [6]:
cancerdata = datasets.load_breast_cancer()
cancerdata.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [13]:
X = cancerdata.data
y = cancerdata.target

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [14]:
X = scaler.fit_transform(X)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.3)

In [16]:
from sklearn.svm import SVC

In [17]:
svclassifier = SVC(kernel = 'linear')
svclassifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [18]:
y_pred = svclassifier.predict(X_test)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 52   4]
 [  1 114]]
             precision    recall  f1-score   support

          0       0.98      0.93      0.95        56
          1       0.97      0.99      0.98       115

avg / total       0.97      0.97      0.97       171



In [21]:
svclassifier = SVC(kernel = 'poly', degree = 8)
svclassifier.fit(X_train,y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 17  39]
 [  1 114]]
             precision    recall  f1-score   support

          0       0.94      0.30      0.46        56
          1       0.75      0.99      0.85       115

avg / total       0.81      0.77      0.72       171



In [22]:
svclassifier = SVC(kernel = 'rbf')
svclassifier.fit(X_train,y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 52   4]
 [  1 114]]
             precision    recall  f1-score   support

          0       0.98      0.93      0.95        56
          1       0.97      0.99      0.98       115

avg / total       0.97      0.97      0.97       171



In [23]:
svclassifier = SVC(kernel = 'sigmoid')
svclassifier.fit(X_train,y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 52   4]
 [  2 113]]
             precision    recall  f1-score   support

          0       0.96      0.93      0.95        56
          1       0.97      0.98      0.97       115

avg / total       0.96      0.96      0.96       171

