In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm, datasets
%matplotlib inline

In [19]:
bankdata = pd.read_csv('../../data/banknote_authentication.csv')
bankdata.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [20]:
X = bankdata.drop(['Class'],axis=1)
y = bankdata['Class']

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [22]:
X = scaler.fit_transform(X)

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.3)

In [24]:
from sklearn.svm import SVC

In [25]:
svclassifier = SVC(kernel = 'linear')
svclassifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [26]:
y_pred = svclassifier.predict(X_test)

In [27]:
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[222   7]
 [  0 183]]
             precision    recall  f1-score   support

          0       1.00      0.97      0.98       229
          1       0.96      1.00      0.98       183

avg / total       0.98      0.98      0.98       412



In [32]:
svclassifier = SVC(kernel = 'poly')
svclassifier.fit(X_train,y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[222   7]
 [  0 183]]
             precision    recall  f1-score   support

          0       1.00      0.97      0.98       229
          1       0.96      1.00      0.98       183

avg / total       0.98      0.98      0.98       412



In [30]:
svclassifier = SVC(kernel = 'rbf')
svclassifier.fit(X_train,y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[229   0]
 [  0 183]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       229
          1       1.00      1.00      1.00       183

avg / total       1.00      1.00      1.00       412



In [31]:
svclassifier = SVC(kernel = 'sigmoid')
svclassifier.fit(X_train,y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[189  40]
 [ 47 136]]
             precision    recall  f1-score   support

          0       0.80      0.83      0.81       229
          1       0.77      0.74      0.76       183

avg / total       0.79      0.79      0.79       412

